Create Allocated Tables
TemwaNyirenda/database-project pull request #2
Opened 2024-02-08 18:50 UTC by jordanbmnt

Created the `BBDTotalAllocation` ,`StudentInfo` and  `ApprovalStatusIndex` tables and define their attributes, keys, and constraints.

- I decided to change the name of `StudentIndex` to `ApprovalStatusIndex` for readabilty.

2024-02-08 18:51 UTC, jordanbmnt commented
Also please ignore the first push. This was to test if we can push directly to main.

2024-02-09 09:53 UTC, TemwaNyirenda submitted a review, later dismissed
Make changes

2024-02-09 09:54 UTC, ThahGum approved these changes, later dismissed

2024-02-09 10:00 UTC, TemwaNyirenda requested changes

2024-02-09 10:00 UTC, TemwaNyirenda commented on dbDefinition/CreateApprovalStatusIndex.sql
> +  StatusID [int] IDENTITY(1,1),
Square brackets around attribute names

2024-02-11 13:20 UTC, closed without merging